# Generated by Django 6.0.2 on 2026-03-19 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_farmeruser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'warehouse_owner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_warehouses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to='core.croplisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
